### ISSUE TITLE
Trouble while changing resolution to 4k

### ISSUE THREAD

**Issue by hot22shot** [Nonary/ResolutionAutomation#10]
Hi,

I'm using my Sunshine server with 2 Moonlight client :

1. My macbook pro who has a native resolution of 2560 x 1600
2. My desktop PC, native resolution is 3840 x 2160

When I connect with my macbook I have no issue, the Sunshine desktop is resized to 2560 x 1600.
But when I connect with my PC, the resolution does not resize to 4k and I have to do it manually.

Here's a link to the log file https://pastebin.com/31wkz9Jz

Any idea ?

**Comment by Nonary** [comment]
Looks like it might have to do with the refresh rate being set to 65?
Can you try adding this line to the overrides.txt file?

3840x2160x60=3840x2160x65

**Comment by hot22shot** [comment]
Thanks, instead of adding an exception I modified the configuration of the Moonlight client to request a refresh rate of 60 and it worked.
