### ISSUE TITLE
install script can't create scheduled tasks

### ISSUE THREAD

**Issue by sage2050** [Nonary/ResolutionAutomation#11]
![image](https://user-images.githubusercontent.com/48387376/235986873-27029b35-8f18-4893-aea2-c9e90134688a.png)

**Comment by sage2050** [comment]
this cmdlet doesn't like the -user parameter for some reason. I can't figure out how to get it to work in any capacity, so i just removed it. the task was still created with the correct user account. making a pr to remove the parameter and also run a later version of powershell.

**Comment by Nonary** [comment]
fixed with your pr #12
