### ISSUE TITLE
Using AutoHDRSwitch breaks ResolutionAutomation

### ISSUE THREAD

**Issue by scsmartt** [Nonary/ResolutionAutomation#14]
It seems that when using both AutoHDRSwitch and ResolutionAutomation, the resolution is changed but as soon as HDR is toggled, the resolution changes back. AutoResolution was working great before I started using AutoHDRSwitch as well.

**Comment by Nonary** [comment]
What resolution are you trying to change it to? HDR is only supported on TV resolutions like 1920x1080 or 3840x2160 and if you enable HDR on a nonstandard resolution, windows will force it to 1080/2160p

**Comment by molnizzle** [comment]
You can definitely have HDR on 2560x1600, happens to me all the time when HDR script fails.

**Comment by Nonary** [comment]
Closing out for lack of response from original poster.

**Comment by mhbates** [comment]
Same issue here. Native resolution is 1440P. ResolutionAutomation successfully switches to 1080P initially (upon loading Playnite), but after launching a game with HDR, it reverts to the native resolution of 1440P. I'm not using AutoHDRSwitch, though; the HDR enablement is coming from Playnite, which can activate HDR mode on a per-game basis.

**Comment by mhbates** [comment]
I did a bit more testing, and it seems like once you do this (HDR enablement), something changes the resolution back to native (assuming ResolutionAutomation, but not sure); and then, it essentially breaks the script, which keeps throwing "Still waiting for the next event to fire", even after the session is ended. It requires a new session to be started and stopped (possibly more than once) for the script to recover and start functioning normally again.

**Comment by Andy-Voigt** [comment]
Hi there, for me it works if i install first HDRAutoswitch and then ResolutionAutomation.

**Comment by Nonary** [comment]
> I did a bit more testing, and it seems like once you do this (HDR enablement), something changes the resolution back to native (assuming ResolutionAutomation, but not sure); and then, it essentially breaks the script, which keeps throwing "Still waiting for the next event to fire", even after the session is ended. It requires a new session to be started and stopped (possibly more than once) for the script to recover and start functioning normally again.

It's more likely Window is changing resolution back to native when enabling HDR, the fix there would be to install the HDR script before the resolution script, that way the HDR setting is applied before the resolution changes.

I havent seen this behavior on my machine though
