### ISSUE TITLE
Not working on win 11

### ISSUE THREAD

**Issue by gaming09** [Nonary/ResolutionAutomation#16]
I cant seem to get it to actually switch resolutions on windows 11 the logs say it does but no switching happens on the host side .  (i have the custom resolution set in Nvidia control panel) 

Also anyway to hide the "log file" cmd prompt

I couldnt get https://github.com/Nonary/ResolutionAutomation/releases/tag/precommand to run at all, running install command didnt install a task or anything) 

**********************
Windows PowerShell transcript start
Start time: 20230529190125
Username: GAMINGPC\Gamer1
RunAs User: GAMINGPC\Gamer1
Configuration Name: 
Machine: GAMINGPC (Microsoft Windows NT 10.0.22621.0)
Host Application: powershell.exe -windowstyle hidden -executionpolicy bypass -file C:\Program Files\Sunshine\ResMatch\GS_SS-MatchResolution.ps1
Process ID: 67228
PSVersion: 5.1.22621.963
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.963
BuildVersion: 10.0.22621.963
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\log.txt
Attempting to set resolution to the following values

Name                           Value
----                           -----
width                          2176
height                         1812
refresh                        90
Attempting to set resolution to the following values
CurrentRefreshRate             120
CurrentVerticalResolution      1440
CurrentHorizontalResolution    2560
Resolution changed successfully.
Attempting to set resolution to the following values
width                          2176
height                         1812
refresh                        90

**Comment by Nonary** [comment]
width 2176
height 1812
refresh 90

^ That resolution does not appear to exist on your PC. You need to add it.

And this works on Windows 11, just so you know.

**Comment by gaming09** [comment]
> width 2176 height 1812 refresh 90
> 
> ^ That resolution does not appear to exist on your PC. You need to add it.
> 
> And this works on Windows 11, just so you know.

![image](https://github.com/Nonary/ResolutionAutomation/assets/31674130/c124cb31-f8b0-4096-be22-f00da423c374)
maybe not a windows 11 problem - this seems to be intermediate. 
Also the command window remains open showing the log file any way to suppress this?

**Comment by gaming09** [comment]
![image](https://github.com/Nonary/ResolutionAutomation/assets/31674130/295563d6-3404-41c7-a664-25e11d42f100)
that seems to be persistent even with the hidden flag on the task

**Comment by Nonary** [comment]
That's a windows 11 bug, you need to set default terminal to windows console host.

Also, the resolution **must** show up on display settings in windows, not just nvidia settings.

**Comment by gaming09** [comment]
> That's a windows 11 bug, you need to set default terminal to windows console host.
> 
> Also, the resolution **must** show up on display settings in windows, not just nvidia settings.

That did it thanks,

What's the deal with the precommand one is there a config that has to go into sunshine?

**Comment by Nonary** [comment]
> > That's a windows 11 bug, you need to set default terminal to windows console host.
> 
> > 
> 
> > Also, the resolution **must** show up on display settings in windows, not just nvidia settings.
> 
> 
> 
> That did it thanks,
> 
> 
> 
> What's the deal with the precommand one is there a config that has to go into sunshine? 

Not sure what you mean, it works fine for me. I did an update this morning that fixes an issue for sunshine 0.20 users, so redownload the release and try again?
