### ISSUE TITLE
Script randomly changes resolution after disconnecting client.

### ISSUE THREAD

**Issue by kevidoplz** [Nonary/ResolutionAutomation#18]
The script itself works as intended, but whenever a client disconnects, it goes back the original resolution of the host like normal, but then would randomly quickly change the resolution back to the client's resolution for a split second for example:

Host is at 1920x1080, Client is at 1920x1200. 

When the client disconnects from the host, the resolution goes from 1920x1200 back to 1920x1080 like intended but randomly reverts back to 1920x1200 for a split second and then goes back to 1920x1080 despite the client not being connected anymore. This causes the host display to turn black for a few seconds every time it happens.

The only way I can stop this from happening is if I quit and re-open Sunshine,

**Comment by Nonary** [comment]
Please upload the log.txt file in the scripts folder

**Comment by Nonary** [comment]
No response received
