### ISSUE TITLE
Restore the original resolution.

### ISSUE THREAD

**Issue by 009107** [Nonary/ResolutionAutomation#2]
The script successfully change the resolution of the host to the device I am connecting but failed to restore the resolution after I terminated the connection.

**Comment by Nonary** [comment]
This should be fixed in latest release, assuming you were also a Parsec user

**Comment by 009107** [comment]
Unfortunately, I am not a Parsec user and this is a new clean PC only with Steam, games, and moonlight installed.
What information can I offer to help to solve the situation?

**Comment by Nonary** [comment]
You would basically need to debug it on your side, so realistically without programming skills that will be difficult. 

As a workaround I would suggest changing the Set-ScreenResolution call when the stream ends to use hardcoded values instead, such as instead of referencing $hostResolution.CurrentHorizontalResolution you would change that to 1920 for example.

**Comment by 009107** [comment]
Thank you for your help, I will try you solution once I got a chance.
Love.

**Comment by RealZack** [comment]
Hello there,

Juste to let you know I have the same problem, using sunshine too as server

**Comment by Nonary** [comment]
> Hello there,
> 
> Juste to let you know I have the same problem, using sunshine too as server
> 
> EDIT : to give more information, I test from android moonlight client and from another pc, both on disconnected do not put back the original resolution.
> 
> I also replace the line 250 of GS_SS-MatchResolution.ps1 and reinstall the task with the above
> 
> Set-ScreenResolution -Width 2560 -Height 1440 -Freq $hostResolution.CurrentRefreshRate
> 
> it seems like this line is not triggered on the client disconnect

You need to hard code the refresh rate too, basically don’t reference the variable at all.

**Comment by RealZack** [comment]
I tried but no change unfortunatly :/

**Comment by AbrahamHuitron** [comment]
I'm dealing with the same issue right now, I hard coded the values into line 250 but no success.

**Comment by Nonary** [comment]
I changed the logic of the resolution swap in this pre-release, let me know if it works for you or not.

https://github.com/Nonary/ResolutionAutomation/releases/tag/precommand_beta

**Comment by AbrahamHuitron** [comment]
I removed the latest release and ran this pre-release but I'm still getting the same issue unfortunately. The resolution doesn't switch back. Anything else I should give a shot?

**Comment by Nonary** [comment]
> I removed the latest release and ran this pre-release but I'm still getting the same issue unfortunately. The resolution doesn't switch back. Anything else I should give a shot?

Yes, please download the release again. I added logging, can you upload that log if it failed to work for you?

**Comment by AbrahamHuitron** [comment]
Tried again but still no change. Where can I find the logs at?

**Comment by Nonary** [comment]
> Tried again but still no change. Where can I find the logs at?

It's in the same folder as the script, named log.txt

**Comment by Nonary** [comment]
@AbrahamHuitron Remember to install it again, if you don't it will not have the correct paths.

**Comment by AbrahamHuitron** [comment]
I have veen overwriting the previous files and running the files again. I will try again in a few hours. One question though, when right click and run with PowerShell it runs quick but closes. Is that the normal expectation?

**Comment by Nonary** [comment]
> I have been overwriting the previous files and running the scripts again fresh. I will try again in a few hours. One question though, when right click and run with PowerShell it runs quick but closes. Is that the normal expectation?

For the ResolutionMatcher.ps1 script yes, that is launched before you start streaming and will hide in the background. 
The installer script should not be closing out.

**Comment by AbrahamHuitron** [comment]
Yeah when I'm right clicking on the install script it opens up a Powershell script but really quickly closes it out. The latest version you uploaded, not sure if it's running or not, but doesn't change the resolution anymore.

**Comment by AbrahamHuitron** [comment]
Also, I have your AutoHDR script active and it's requirements set at the moment too by the way, i.e. Windows Console Host, etc. so not sure if any of those are clashing with these prerelease requirements. AutoHDR is working fine by the way.

**Comment by AbrahamHuitron** [comment]
Hey there, I came back and wanted to let you know I figured out the issue. For some reason everytime I was running your prerelease version through the PowerShell (I was following your steps to run To install, right click the Install_as_Precommand.ps1 file and select "Run With Powershell".). The PowerShell window would just open then immediately close. I'm an admin on my computer but what I ended up doing was just right clicking and editing the file, which then defaulted it to open PowerShell completely.

Within here I was able to see the error message the script was giving me forcing the close. the .ps1 file is not digitally signed. So I used this to temporarily bypass and run the script.

https://caiomsouza.medium.com/fix-for-powershell-script-not-digitally-signed-69f0ed518715

All went through, the script works great and the resolution matching is working now!

The only other thing I would suggest is maybe you could set the script to revert back to the original resolution not when we CLOSE out the application we are running on Moonlight, but when we actually QUIT the application from the Moonlight interface. I'm playing on my Android handheld and when I close the app out to go to another task the resolution reverts back to my PCs but streaming is still essentially "happening". Just a thought. Thanks!

**Comment by Nonary** [comment]
@AbrahamHuitron I forgot I had developer mode enabled in Windows, which is why the script didn't work for regular users. I have fixed this now, the new releases now include a batch file which launches the powershell window with the correct parameters needed.

As for your second question, you would need to setup your application in Sunshine with a command if you want it to automatically terminate the session or revert back after that. Otherwise, ending the stream in Moonlight will revert resolution regardless.

**Comment by AbrahamHuitron** [comment]
Awesome, I will update when I get home.

Oh that's right. I'm using Playnite launcher only as the my single app in
Moonlight and it was giving me issues whenever I set the commands to
monitor it. Mainly if the app is already running or not. So yeah I guess
it's not an issue on your end you're right thanks!

**Comment by Nonary** [comment]
As far as I am aware the recent changes to my script should have resolved all the edge cases where it was not properly pulling the client resolution to restore. I am going to close out this issue as resolved at this point.
