### ISSUE TITLE
Maybe not setting right resolution?

### ISSUE THREAD

**Issue by jriker1** [Nonary/ResolutionAutomation#29]
I have been using MonitorSwapAutomation successfully for a while.  Now no longer have access to my physical monitor Problem with ResolutionAutomation maybe?  The logs for monitorswap claim it set the monitor back to the physical monitor.  The problem though ResolutionAutomation shows this and I'm not currently connected:

```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to 1920 x 1080 x 60
Resolution changed successfully.
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 3840 x 2160 x 60
Resolution changed successfully.
**********************
Windows PowerShell transcript end
End time: 20230925164152
```

Problem I'm having is the monitor attached to the computer is a older 17" LCD 1U rack mount KVM monitor.  Looks like the last resolution change was to 4k which would be the dummy dongle.  Is it possible ResolutionAutomation is setting the wrong resolution and that's why the monitor isn't displaying?   Not even sure if ResolutionAutomation touches the primary display resolution.

MonitorSwap claims it set the monitor back to active but no clue how to tell:

```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      MonitorSwapp... BackgroundJob   Running       True            localhost            ...
3      MonitorSwapp... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Dummy plug activated
Request to terminate has been processed, script will now revert monitor configuration.
Attempting to set primary screen, some displays may not activate until you return to the computer
Monitor(s) have been successfully restored.
Dummy Plug has been successfully deactivated!
**********************
Windows PowerShell transcript end
End time: 20230925164154
```

**Comment by Nonary** [comment]
Yes, the resolution swap changes the primary monitors resolution. You need to make sure the monitor swap happens first, if it changes it too quickly you can adjust the sleep timers in the script to wait a little longer before it does it.

As for when it reverts, it does it backward. So it will first revert the resolution, then swap back to main monitor (provided you have the swap happening before the resolution change like mentioned earlier)
