### ISSUE TITLE
Scale Setting Support?

### ISSUE THREAD

**Issue by Skates1616** [Nonary/ResolutionAutomation#3]
Any chance of adding a  setting to match scaling also?  Or would it be possible to create an option to adjust scaling?

The reason I ask, is its hard to work at 4K resolution at 100% scaling.  I typically use 300%...

**Comment by Nonary** [comment]
Unfortunately there aren't any "official" DPI scaling API calls provided by Windows that can change the monitor scaling specifically. The ones online are either using undocumented Windows API's or reverse engineering. Which means they would be prone to breaking and I don't want to set myself into supporting an API that isn't even officially supported by Microsoft.
