### ISSUE TITLE
Unable to start Sunshine after installation.

### ISSUE THREAD

**Issue by seflerZ** [Nonary/ResolutionAutomation#32]
After executing the install.bat with cmd.exe. The Sunshine service is unable to start until removing the resolution component.

```
[nv_rc] -- [vbr]
[nv_coder] -- [cavlc]
[sunshine_name] -- [GameCenter]
[global_prep_cmd] -- [[{"do":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"C:\\Users\\sefler\\桌面\\ResolutionAutomation-main\\ResolutionMatcher.ps1\"","elevated":"false","undo":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"C:\\Users\\sefler\\桌面\\ResolutionAutomation-main\\ResolutionMatcher-Functions.ps1\" True"}]]
[origin_pin_allowed] -- [wan]
terminate called after throwing an instance of 'boost::wrapexcept<boost::property_tree::json_parser::json_parser_error>'
  what():  <unspecified file>(1): invalid code sequence
```

**Comment by seflerZ** [comment]
Confirmed it's caused by non ASICII charaters involving. Change the installation directory to to "C:/" solves this problem.

**Comment by Nonary** [comment]
This is a bug in Sunshine specifically, but generally speaking this is a widescale problem in a lot of programs. Anytime you have a non-ascii supported username a lot of apps will just break. The workaround is to save it outside of your user profile (so it doesn't have the non-ascii characters) but you can also try this workaround:  https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30#issuecomment-1172924002
