### ISSUE TITLE
Resolution fallback to default when HDR switch

### ISSUE THREAD

**Issue by qiin2333** [Nonary/ResolutionAutomation#33]
client resolution: 3200x1440@120
default host resolution: 3840x2160@120

version: v2.0.15_gfe

**Comment by Nonary** [comment]
This is a known issue with NVIDIA Custom Resolutions, you need to modify the registry or try using CRU to add the resolution instead:

https://www.avsforum.com/threads/nvidia-custom-resolutions.3127652/#post-59354962
