### ISSUE TITLE
Not changing host resolution with client resolution

### ISSUE THREAD

**Issue by falzon-io** [Nonary/ResolutionAutomation#34]
Sunshine 0.21.0
ResolutionAutomation v2.2.0

Not changing host resolution with client resolution. never sets host to 1920 x 1080 x 60, or any resolution for that matter. i've also reinstalled ResolutionAutomation via provided scripts.

log below: Does not seem to state "Resolution changed successfully" after setting screen resolution from client.
**********************
Transcript started, output file is .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to 1920 x 1080 x 60
Still waiting for the next event to fire...
Still waiting for the next event to fire...
Still waiting for the next event to fire...
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 5120 x 1440 x 240
Resolution changed successfully.
**********************

**Comment by Nonary** [comment]
Looks like it is having troubles with 1080p 60hz, can you confirm this resolution is available on your host? Otherwise, you could try adding this to overrides.txt
1920x1080x60=1920x1080x240

**Comment by Nonary** [comment]
No response from user
