### ISSUE TITLE
[Windows 11 -> MacOS] Resolution doesn't change

### ISSUE THREAD

**Issue by Maikenvv** [Nonary/ResolutionAutomation#35]
### Versions
**Sunshine (Windows 11)**
v0.21.0

**ResolutionAutomation** 
v2.2.0

**Moonlight (MacOS)**
v5.0.0

### Issue
When I launch my desktop from Moonlight on MacOS, the resolution doesn't change. This means I have black bars at the top and bottom of the screen of my Mac. I can see in the logs of ResolutionAutomation that it says the resolution has been changed, but it just didn't happen.

### Steps I've already taken
**Windows 11**
- Terminal has been set to Windows Console Host
- Resolutions have been added to Sunshine, both scaled and non-scaled.
- Rebooted Sunshine
- Rebooted PC

**MacOS**
- Tried scaled resolution
- Tried scaled resolution
- Re-installed Moonlight

### Log
I've attached both the log for ResolutionAutomation and Sunshine.
[Log ResolutionAutomation.txt](https://github.com/Nonary/ResolutionAutomation/files/13231118/Log.ResolutionAutomation.txt)
[Log Sunshine.txt](https://github.com/Nonary/ResolutionAutomation/files/13231119/Log.Sunshine.txt)

**Comment by Nonary** [comment]
Your host needs to have the following resolution added:

3456 x 2234 x 120

You can do that with NVIDIA control panel

**Comment by Nonary** [comment]
No response from user
