### ISSUE TITLE
It doesn't stop making logs

### ISSUE THREAD

**Issue by Alexroyer** [Nonary/ResolutionAutomation#37]
Every 15 minutes or so it prompts a PowerShell saying it is transcribing to a log.txt even when I stopped the stream hours ago

**Comment by Nonary** [comment]
Please upload that log file

**Comment by Alexroyer** [comment]
[log.txt](https://github.com/Nonary/ResolutionAutomation/files/13327899/log.txt)

Could it be the reason it doesn't stop making logs that I changed the unzipped name from "ResolutionMatcher" to "ResolutionMatcher_GeForce_Stream" ?

**Comment by Nonary** [comment]
The Geforce Experience version is meant to be always running at all times, that is how it works. Its only Sunshine that allows it to be ran on demand.

**Comment by Nonary** [comment]
As mentioned, the Geforce Experience version is very much like a background service and will write to the log file. Upgrade to Sunshine if you prefer an on-demand solution.
