### ISSUE TITLE
Console popup every few minutes | v2.20

### ISSUE THREAD

**Issue by David-Moreira** [Nonary/ResolutionAutomation#42]
Hello,

I just migrated to the new version **2.1.0+** from an older version, it is indeed faster / smoother, but I noticed I keep getting console popups from time to time, I noticed we now have a task scheduler entry, is this necessary?
![image](https://github.com/Nonary/ResolutionAutomation/assets/22283161/b4ebf154-5555-45f0-bc6b-93704deb636b)

**Comment by Nonary** [comment]
If you're using the legacy version, the one meant for Geforce Experience, yes this is required. Only the Sunshine version can run on demand since it supports scripts on launch and exiting.

**Comment by David-Moreira** [comment]
Great, Thanks!
