### ISSUE TITLE
Does not always set the Active Signal Resolution

### ISSUE THREAD

**Issue by ozitvogel** [Nonary/ResolutionAutomation#43]
Would it be possible that the tool also forces the active signal resolution ?
For some reasons, it does not.
I my setup I have my monitor set at 4K 3840x2160@60
I added my Lenovo Go's native resolution in NVIDIA's Custom Resolution tool 2560x1600@144
When I start Moonlight, the Desktop resolution is at 2560x1600@60 and the Active signal stays at 3840x2160@60
Also the 144 refresh rate does not appear in the refresh rate popup. Need to set it in the advanced tab.

Maybe this is related to the NVIDIA Custom Resolution tool ?
I managed to have everything running fine headless using the fake lddSampleDriver.

**Comment by Nonary** [comment]
You'll have to use CRU to add the custom resolution if NVIDIA control panel is unable to add it successfully.

Or alternatively, the IddSampleDriver like you discovered.

Windows will sometimes downscale a resolution, this is why you're noticing an active signal resolution and desktop resolution.
