### ISSUE TITLE
Host resolution not changing.

### ISSUE THREAD

**Issue by acevisai** [Nonary/ResolutionAutomation#47]
**********************
Windows PowerShell transcript start
Start time: 20240114230346
Username: 
RunAs User: 
Configuration Name: 
Machine:  (Microsoft Windows NT 10.0.19045.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Users\Ace\Documents\ResolutionAutomation\staging\ResolutionMatcher.ps1 -async True
Process ID: 5608
PSVersion: 5.1.19041.3930
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3930
BuildVersion: 10.0.19041.3930
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Setting screen resolution to 1920 x 1200 x 90
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 2560 x 1440 x 144
Resolution changed successfully.
**********************
Windows PowerShell transcript end
End time: 20240114230355
**********************

I created a custom resolution for 1920x1200x90 in nvidia settings and set it in the overrides.txt

The overrides.txt:

1280x800x90=1920x1200x90 # For Steam Deck users, typically if the user has a 4k screen this resolution is supported and will auto swap aspect ratios for them.

**Comment by Nonary** [comment]
You'll have to use CRU if NVIDIA Control panel fails to work

**Comment by acevisai** [comment]
Got it. I'll update after using CRU
