### ISSUE TITLE
使用aster软件的主机修改分辨率失败，有其他分辨率修改方案么

### ISSUE THREAD

**Issue by rufengsuixing** [Nonary/ResolutionAutomation#56]
![图片](https://github.com/Nonary/ResolutionAutomation/assets/22387141/20108d9e-4f1c-44e7-baa0-24c97962b4cd)
手动调整分辨率后显示器信息如下
![图片](https://github.com/Nonary/ResolutionAutomation/assets/22387141/844a6505-90c8-4b37-a16a-0e5b1c27a239)

log如下
**********************
Windows PowerShell 脚本开始
开始时间: 20240303191245
用户名: xx
RunAs 用户: xx
配置名称: 
计算机: DESKTOP-0JI8RA2 (Microsoft Windows NT 10.0.22631.0)
主机应用程序: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Users\jie\Desktop\tools\ResolutionAutomation-main\ResolutionMatcher.ps1 -async True
进程 ID: 39608
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
已启动脚本，输出文件为 .\log.txt

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      ResolutionMa... BackgroundJob   Running       True            localhost            ...
3      ResolutionMa... BackgroundJob   Running       True            localhost            ...
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
Before Override: 3200 x 1440 x 60
After Override: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Current Resolution: 3840 x 2160 x 60
Expected Requested Resolution: 3200 x 1440 x 60
Setting screen resolution to 3200 x 1440 x 60
Processing event: End
Setting screen resolution to 3840 x 2160 x 60
Resolution changed successfully.
**********************
Windows PowerShell 脚本结束
结束时间: 20240303191257
**********************

**Comment by Nonary** [comment]
Do not duplicate displays. If you are using a dummy plug, it must be set as the primary display, and you must turn off the other displays. For automation of this process, refer to https://github.com/Nonary/MonitorSwapAutomation. Additionally, you should use CRU to add the custom resolution.
