### ISSUE TITLE
Stuck @29-31FPS with script installed

### ISSUE THREAD

**Issue by youdontknowmu** [Nonary/ResolutionAutomation#57]
Hi there !

Thanks for this marvellous script, it works perfectly fine for the resolution match part !

The only issue I have is as follow :

Host =
Ryzen 3800x 
GPU 3080 10Go
Monitor 3440*1440 @144hz
Sunshine latest version

Client = 
Nvidia Shield Pro

-------BEFORE installing ResolutionAutomation----------
Start Moonlight
Settings = 1080p + 60fps asked NVENC preferred
Start SteamBigPicture Stream
Start Baldur's gate 3
Runs perfectly fine @60fps but the wrong aspect ratio.
--------------------------------------------------------------

-------AFTER installing ResolutionAutomation----------
Start Moonlight
Settings = 1080p + 60fps asked NVENC preferred
Start SteamBigPicture Stream
Good ratio
Start Baldur's gate 3
Runs between 29,1 and 31fps but with the good ratio.
--------------------------------------------------------------

I didn't change anything in the given override file, it stills contain only
"1280x800x60=2560x1600x60 # For Steam Deck users, typically if the user has a 4k screen this resolution is supported and will auto swap aspect ratios for them."

I don't understant why it seems to cap the FPS around 30
(but only in game, because I manage to get 58fps by moving the mouse on the steam big picture app)

Event if it works perfectly without your script, I still checked the in game settings, no v-sync, no frame limit.

Do you have any idea why I stumble on this problem ? :)

Thanks for any answer !

**Comment by Nonary** [comment]
This is a Sunshine issue, please reach out to the Moonlight and or Sunshine discords for support on this issue.

**Comment by youdontknowmu** [comment]
Ok thanks, I'll do this.
Do you have any technical informations that I could give them in order to help ?
(when I change the resolution manually, it works perfectly), what could cause you script's resolution change to conflict with sunshine/moonlight ?)
