### ISSUE TITLE
Is There a Way to Change DPI and HDR Status on Streaming?

### ISSUE THREAD

**Issue by HopleViorn** [Nonary/ResolutionAutomation#58]
Some of my devices do not support HDR and some of them are too small in screen size. So is there any method to change the DPI
and HDR on/off?

**Comment by Nonary** [comment]
https://github.com/Nonary/AutoHDRSwitch

As for DPI, no there isn't a publicly exposed API that allows you to change the DPI. Microsoft wants developers to set DPI per application, even though literally zero applications do that.
