### ISSUE TITLE
Issue with multiple monitors

### ISSUE THREAD

**Issue by nimaim** [Nonary/ResolutionAutomation#59]
I have two monitors: one @ 2560x1440 60 hz and the other at 3440x1440 120 hz. I launch Steam big picture on my lower res monitor and have a custom profile in Nvidia control panel to accept a 2340x1080 resolution of my Pixel 5. This seems to work just fine and the game scales to the proper resolution on the monitor and is full screen and sharp on the phone. 

The issue is when you close out of Moonlight, it sets BOTH my monitors back to 2560x1440 60 hz (not just the active one) and I have to manually set the ultrawide back to its native res and 120 hz. This is more of a nuisance than anything as you can always set it back manually but would be nice to have fixed and automated in the script if possible.

**Comment by Nonary** [comment]
Install https://github.com/Nonary/MonitorSwapAutomation, that way only one monitor is active during streaming.
