### ISSUE TITLE
Resolution doesn`t change on my monitor

### ISSUE THREAD

**Issue by majstermsi** [Nonary/ResolutionAutomation#60]
Script installed without any errors via .bat
Monitor is samsung 34" with native 3440x1444. Legion go is 2560x1600.  When I start moonlight I setup native res of legion go in settings. Resolution doesn`t change of my montor in effect I got wrong resolution on Legion go.  I tried to setup other resolutions on moonlight however there is no any reaction from script Resolution Automation to change res on host (samsung monitor).
Log:
Current Resolution: 3440 x 1440 x 175
Expected Requested Resolution: 2560 x 1600 x 144
Setting screen resolution to 2560 x 1600 x 144
Current Resolution: 3440 x 1440 x 175
Expected Requested Resolution: 2560 x 1600 x 144
Setting screen resolution to 2560 x 1600 x 144
Request to terminate has been processed, script will now revert resolution.
Setting screen resolution to 3440 x 1440 x 175
Resolution changed successfully.

In logs everything ok however no reaction on monitor and Legion. Resolution on monitor is permanently 3440 x 1440 x 175.

What went wrong?

**Comment by Nonary** [comment]
You need to add the resolutions on the host, using CRU or NVIDIA Control Panel
