### ISSUE TITLE
About Locked screen

### ISSUE THREAD

**Issue by my57575757** [Nonary/ResolutionAutomation#61]
The program does not work when the Windows locks the screen

**Comment by my57575757** [comment]
![image](https://github.com/Nonary/ResolutionAutomation/assets/60951130/b09dccb4-b8c7-477b-aed3-93fe03e81899)

**Comment by my57575757** [comment]
I found that if I unlocked the screen fast enough, he would still work.

**Comment by Nonary** [comment]
I am unable to replicate this issue, can you explain your setup more. Also if you're doing anything non-standard (such as disabling UAC or logging in with local admin accounts) please include those details.

**Comment by Nonary** [comment]
No response
