### ISSUE TITLE
doesnt work at all

### ISSUE THREAD

**Issue by frootloop88** [Nonary/ResolutionAutomation#65]
![Screenshot 2024-05-14 110421](https://github.com/Nonary/ResolutionAutomation/assets/47665953/ceaa5de1-7e59-45b4-93e2-c2ec2bbf49c6)

**Comment by Nonary** [comment]
You are using the pre-release version, which is still in beta at this point in time, if you intend to use the production version please select the latest release instead

With that being said, I believe I have fixed this bug on this version: https://github.com/Nonary/ResolutionAutomation/releases/download/v3.0/BETA_ResolutionMatcher_v3.zip

**Comment by e3ndr** [comment]
Hey @Nonary, I'm not OP but I tried the latest beta (`_v3`) and I get this when loading moonlight:
```
**********************
Windows PowerShell transcript start
Start time: 20240516160810
Username: DESKTOP-QA28AVD\pigal
RunAs User: DESKTOP-QA28AVD\pigal
Configuration Name: 
Machine: DESKTOP-QA28AVD (Microsoft Windows NT 10.0.22621.0)
Host Application: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command & 'C:\Users\pigal\Documents\programs\ResolutionMatcher\StreamMonitor.ps1' -scriptName ResolutionMatcher -sib 1
Process ID: 27160
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_1715875691.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
DEBUG: Function Get-HostResolution called
PS>TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
>> TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
>> TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
**********************
Windows PowerShell transcript end
End time: 20240516160815
**********************
```

I also briefly get a path error when it first starts that isn't visible in the above log:
![wouVUfvT19](https://github.com/Nonary/ResolutionAutomation/assets/33337309/826ca59e-ea2e-4159-bbe1-b5c8c374e2aa)

**Comment by Nonary** [comment]
@e3ndr Fixed that, you'll have to download the release again

**Comment by e3ndr** [comment]
> @e3ndr Fixed that, you'll have to download the release again

Getting further! Now I've run into the same problem as stable, where it doesn't work at all :(
[Latest log](https://github.com/Nonary/ResolutionAutomation/files/15343197/log_1715897751.txt)

**Comment by Nonary** [comment]
> > @e3ndr Fixed that, you'll have to download the release again
> 
> Getting further! Now I've run into the same problem as stable, where it doesn't work at all :( [Latest log](https://github.com/Nonary/ResolutionAutomation/files/15343197/log_1715897751.txt)

The logs show that your PC does not have 1920x1080 available at 30hz, you need to add it with NVIDIA Custom Resolutions, or use CRU (https://customresolutionutility.net/) to add 1920x1080@30hz if you cant get it to work with the nvidia control panel

**Comment by e3ndr** [comment]
> > > @e3ndr Fixed that, you'll have to download the release again
> 
> > 
> 
> > Getting further! Now I've run into the same problem as stable, where it doesn't work at all :( [Latest log](https://github.com/Nonary/ResolutionAutomation/files/15343197/log_1715897751.txt)
> 
> 
> 
> The logs show that your PC does not have 1920x1080 available at 30hz, you need to add it with NVIDIA Custom Resolutions, or use CRU (https://customresolutionutility.net/) to add 1920x1080@30hz if you cant get it to work with the nvidia control panel

🤦 i don't know how i missed that. appreciate the help!

**Comment by Nonary** [comment]
Resolved on latest beta release
