### ISSUE TITLE
v3.0 Beta unable to change resolution

### ISSUE THREAD

**Issue by Peetey** [Nonary/ResolutionAutomation#66]
I updated to the new v3.0 release, but the resolution no longer seems to be adjustable. Prior to the update, I had successfully used this software with both a virtual IDD display and my Steam Deck. I updated the installation by replacing the old files with the new version, reinstalling the script, and then configuring the new settings.json file. I've tried setting different resolutions, but none of them seem to take effect. Here is my log file for reference.

```
**********************
Windows PowerShell transcript start
Start time: 20240520021923
Username: DESKTOP\User
RunAs User: DESKTOP\User
Configuration Name: 
Machine: DESKTOP (Microsoft Windows NT 10.0.22631.0)
Host Application: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -Command & 'C:\Users\User\Documents\ResolutionAutomation\StreamMonitor.ps1' -scriptName ResolutionMatcher -sib 1
Process ID: 16368
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\logs\log_2024_05_20_02_19_23.txt
Waiting for the next event to be called... (for starting/ending stream)
Processing event: Start
PS>TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
>> TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
>> TerminatingError(New-Object): "Cannot find type [DisplaySettings+DEVMODE]: verify that the assembly containing this type is loaded."
**********************
Windows PowerShell transcript end
End time: 20240520021924
**********************
```

**Comment by Nonary** [comment]
You're missing the internals folder, please download the script again

**Comment by Nonary** [comment]
Yeah I think you uncommented the comment portion instead of the json node itself.

Correct: 

```
// Comment
{
}
```

Incorrect
```
Comment
{
}
```

I believe this is something AI would have caught instantly, you can try using ChatGPT.com or Bing to describe the issue and it will fix the problem for you.

**Comment by Peetey** [comment]
I did double check and nothing was wrong so I'm quite sure it was Ctrl+S Notepad++ messing the file up for some reason. Using the Save As menu did fix everything and now the script works perfectly. Thanks!

Here is my settings.json lines for reference:

```
        // Recommended for Steam Deck Users, Uncomment to enable!
         {
             "client": {"width": 2560, "height": 1600, "refresh": 90},
             "host": {"width": 3840, "height": 2400, "refresh": 90}
         }
```
