### ISSUE TITLE
Switching HDR on/off during stream causes resolution to revert to starting one

### ISSUE THREAD

**Issue by KlosiakMK** [Nonary/ResolutionAutomation#67]
Hi,

I noted a bit of a problem when using the script on my setup. I have 3840x1600 monitor and I am streaming in 3840x2160. The custom resolution of 4K 120Hz is present. I am streaming Windows 10 desktop to my 4K TV and when stream is started I launch games from the streamed desktop. Some of games have HDR support and some not. I am using HDRTray button in tray area to easily turn on and off HDR mode before launching a game. The scenario that fails is for example:

1. My windows desktop is in monitor native 3840x1600 SDR mode.
2. I start 4K stream in Moonlight of my Win 10 desktop.
3. Script works perfectly and desktop resolution is immediately changed to 3840x2160 as expected.
4. Using HDRTray icon to turn on HDR.
5. After that HDR is on but resolution of desktop is reverted to 3840x1600 so I can see screen with top and bottom black bars on my 4K TV.

Is it expected behaviour of the script?

When I set Windows desktop to HDR on before starting a stream, script works fine and resolution is upgraded to 4K after launching a stream. Looks like HDR switching is causing the script to revert to native monitor resolution. I have also notice similar behaviour with game called Chernobylite...I mean that when I start it on streamed desktop in-game 4K resolution is fine and stream looks ok but when I close game, streamed desktop is in 3840x1600 instead 3840x2160 and black bars appear.

Raising this as this may be something that can be fixed but I don't know.

And last but not the least I want to thank you @Nonary for this script as it is a huge improvement for me when launching streaming that I don't need to switch manually my desktop to 4K and script does the trick in the most cases and saves my time. Cheers!

**Comment by Nonary** [comment]
Can you try installing my HDR script to automate toggling HDR instead? It might not have the same problem 

https://github.com/Nonary/AutoHDRSwitch/releases/tag/1.2.0

**Comment by KlosiakMK** [comment]
Sure. I can play with your script and check. 

As per my understanding this script turns HDR on based on what Moonlight client asks Sunshine host for when it comes to HDR. 

Taking into account following scenarios to be handled.
1. Starting Win 10 desktop, and when desktop is streamed launch game which runs in HDR, so HDR needs to be switched on.
2. Starting Win 10 desktop, and when desktop is streamed launch game which runs in SDR, so HDR stays in off state?

As per my understanding, if HDR is disabled in Moonlight options then HDR won't be launched for streamed Win 10 desktop but when HDR is enabled in Moonlight options HDR will be turned on automatically for streamed Win 10 desktop. Please let me know if I understand correct?

So this would mean that depending on game I would like to stream I should switch HDR support enabled/disabled in Moonlight options?

**Comment by KlosiakMK** [comment]
Ok, quickly tested and combo of both scripts works as I expected and described above. Using this approach HDR on/off can be done vie Moonlight client settings page.

**Comment by Nonary** [comment]
> So this would mean that depending on game I would like to stream I should switch HDR support enabled/disabled in Moonlight client options?

No you just leave HDR enabled at all times, you benefit from this anyway from games that do not use HDR because it improves the color quality from 8-bit to 10-bit.

> It is a workaround but now I am just curious why HDR switching causes desktop to revert to its native resolution.
The script I linked does not revert resolutions as far as I am aware, you would need to ask whoever developed the other HDR switch program on why it does that.

**Comment by KlosiakMK** [comment]
> No you just leave HDR enabled at all times, you benefit from this anyway from games that do not use HDR because it improves the color quality from 8-bit to 10-bit.

Ok, will try to use the AutoHDRSwitch script as you suggest. Its true that when in Moonlight client HDR is turned on but I stream Win 10 desktop without HR enabled Moonlight statistics overlay show codec as "AV1 10-bit SDR" and when HDR is disabled in Moonlight option this overlay shows only "AV1". With HDR turned on in Moonlight and on desktop that I stream, then it shows "AV1 10-bit HDR". I think that if HDR will be enabled all the times colours for SDR games may be broken as it is Win 10 which is not great when it comes to HDR support. Anyway I will test and share the result.

 > The script I linked does not revert resolutions as far as I am aware, you would need to ask whoever developed the other HDR switch program on why it does that.

Ok, I see. It may be incompatibility between these tools.

One way or another I will play with the scripts more and thanks again for developing these nice tools.
