### ISSUE TITLE
Error code: 503 "Is a display connected and turned on?"

### ISSUE THREAD

**Issue by Staubgeborener** [Nonary/ResolutionAutomation#71]
I am using a widescreen monitor with a 2560x1080 UWFHD resolution which obviously won't fit for a Philips 65OLED804 TV. So i want to use ResolutionAutomation to "fix" this. Without using this tool , i can stream the computer content on the tv but in the wrong resolution. After installing this tool (windows 11, RTX 4080 Super) and start a streaming from moonlight to sunshine i only get a loading screen which stops at a certrain time. After that i get the error `"Host PC returned error: Failed to initialize video capture/encoding. Is a display connected and turned on? (Error code: 503)"`. After uninstalling this tool i can stream from sunshine to moonlight again but with the wrong resolution.

![image](https://github.com/user-attachments/assets/680df1a8-38d5-4701-8e4c-c2001bb1fe00)

**Comment by Nonary** [comment]
Upload the logs of the script

**Comment by Nonary** [comment]
Closing, no response from user.
