### ISSUE TITLE
TV's 4k Resolution broken when using override to set Steam Deck resolution

### ISSUE THREAD

**Issue by Funk3** [Nonary/ResolutionAutomation#73]
Hi!

I have put into override this:

```2560x1600x60=3840x2400x60``` as per your tip in the IDD issue that I posted.

This works flawlessly when I go to play games on my steam deck!

However I also play on my apple tv, and when I go on moonlight and start a game (Yakuza Kiwami in this case), the resolution is 4k, then it swaps over to 1280x800. 

I am able to change the settings to 3840x2160 in the game itself, however I still get black bars on either side. 

What should I do?

Windows 11 2h32
Ryzen 5700x
RTX 3080
IDD HDR Virtual Display
Sunshine v0.23.1

**Comment by Nonary** [comment]
Does the log show it swapping back to 1280x800?

**Comment by Funk3** [comment]
Where can I see the log?

**Comment by Funk3** [comment]
The log only states that the resolution is 1200x800

**Comment by Funk3** [comment]
Sorry for the blast of information here but I believe I have figured out the source of the problem, but am still unsure on how to fix it.

I am using all of your scripts except for the frame rate one. I notice that I have the monitor swapper script working and have the dummy at 1280x800 and it seems to always be going to that resolution because of the script. Is there any way to have multiple resolutions in that script?

**Comment by Nonary** [comment]
> Sorry for the blast of information here but I believe I have figured out the source of the problem, but am still unsure on how to fix it.
> 
> I am using all of your scripts except for the frame rate one. I notice that I have the monitor swapper script working and have the dummy at 1280x800 and it seems to always be going to that resolution because of the script. Is there any way to have multiple resolutions in that script?

Follow these two troubleshooting hints: 

https://github.com/Nonary/MonitorSwapAutomation?tab=readme-ov-file#resolutionautomation-script-isnt-changing-my-resolution-after-connecting-and-or-is-intermittently-working

https://github.com/Nonary/MonitorSwapAutomation?tab=readme-ov-file#resolution-change-when-resuming-or-starting-a-new-stream

Basically, make sure you installed it in the proper order, adjust the sleep delay and ensure dummy plug ID is correct in settings.

That makes sure that the resolution swap happens after the monitor is swapped. If you don’t have a valid dummy ID in the settings, it will revert resolution often.

**Comment by Funk3** [comment]
Thank you very much for your time and patience.

it now portrays 4K on my tv flawlessly, and I can choose 2560x1600 on my steam deck in the options! Thank you very much!
