### ISSUE TITLE
ChatGPT Helper

### ISSUE THREAD

**Issue by RepoExplorer24** [Nonary/ResolutionAutomation#81]
Hello,

I am using the ResolutionAutomation code for personal use and ran into a few issues. The ChatGPT helper you built is unbelievably helpful and solved my issue immediately. Would love to learn more about how you built it. My guess is through specific prompts (I read the two prompts you have in there) but would like to learn more. I'm a noob when it comes to ChatGPT (other than as a user) and would really like to learn more. Could you help me understand how you built it?

Thanks

**Comment by Nonary** [comment]
I made the custom GPT and my instructions and the support script is public in the repo here in case you are curious how it works:

https://github.com/Nonary/ResolutionAutomation/tree/main/ChatGPT
